version: "3"

services:
    ydl:
        # Builds the local Dockerfile image
        # Should probably push this somewhere
        build: ./
        ports:
            - "8080:8080" #host : container
        # restart: unless-stopped
        volumes:
            # Where downloaded videos should go
            - /opt/youtubedownloads:/app/downloads
            # Where the database is
            - /opt/database:/app/db
        environment:
            - APPNAME=YDS
            - ADMINUSER=admin
            - PASSWORD=youtube 
            - TZ=Australia/Melbourne
        #Docker-compose is a piece of kaka and will override the entrypoint in the Dockerfile
        # Compose devs don't care: https://github.com/docker/compose/issues/3140
        # So I need to double up and specify it here
        entrypoint: "./startup.sh"